sonar.projectKey=chandan009s_tetris-cloud-native-pipeline
sonar.organization=chandan009s
sonar.projectName=Tetris-cloud-native-Pipeline
sonar.sources=.
sonar.exclusions=**/*.tar,**/*.yml,**/Dockerfile
sonar.language=js
